// frontend/src/components/CopyButton.svelte
<script lang="ts">
	import { Button } from "$/components/ui/button";
	import { cn } from "$/lib/ui-utils";
	import { ClipboardSetText } from "$wails/runtime/runtime";
	import { Clipboard, ClipboardCheck } from "lucide-svelte";
	import { createEventDispatcher } from "svelte";

	export let toCopy: string = "";

	const dispatch = createEventDispatcher<{
		copy: boolean;
	}>();

	let id: number;
	let isAlertVisible: boolean = false;

	async function copy() {
		if (toCopy === "") {
			return;
		}

		await ClipboardSetText(toCopy);
		isAlertVisible = true;
		dispatch("copy", true);

		clearTimeout(id);

		id = window.setTimeout(() => {
			isAlertVisible = false;
			dispatch("copy", false);
		}, 800);
	}
</script>

<Button
	variant="outline"
	size="icon"
	class={cn(
		$$restProps.class,
		isAlertVisible && "before:content-['Copied!'] before:absolute",
		isAlertVisible && "before:-translate-x-[calc(100%-theme(space.4)+1px)]",
		isAlertVisible && "before:h-10 before:p-2 before:flex before:items-center",
		isAlertVisible && "before:border before:rounded-tl-md before:rounded-bl-md",
		isAlertVisible && "before:bg-background",
		isAlertVisible && "rounded-tl-none rounded-bl-none",
	)}
	on:click={copy}
>
	{#if isAlertVisible}
		<ClipboardCheck class="text-gray-500" />
	{:else}
		<Clipboard class="text-gray-500" />
	{/if}
</Button>

// frontend/src/components/CopyButton.tsx
import { Button } from "@/components/shadcn/button";
import { Clipboard, ClipboardCheck, X } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { ClipboardSetText } from "@wails/runtime/runtime";

type Props = {
  className?: string;
  toCopy(): string;
};

function CopyButton(props: Props) {
  const [copyCount, setCopyCount] = useState(0);

  async function handleClick() {
    const content = props.toCopy();
    if (content === "") {
      return;
    }

    const newCopyCount = copyCount + 1;
    setCopyCount(newCopyCount);

    await ClipboardSetText(content);

    const message =
      newCopyCount === 1 ? "Copied!" : `Copied ${newCopyCount} times!`;
    toast.success(message, {
      cancel: {
        label: <X className="h-4 w-4" />,
        onClick: () => setCopyCount(0),
      },
      onAutoClose: () => setCopyCount(0),
    });
  }

  return (
    <Button
      variant="outline"
      className={props.className}
      size="icon"
      onClick={handleClick}
    >
      {copyCount > 0 ? (
        <ClipboardCheck className="text-gray-500" />
      ) : (
        <Clipboard className="text-gray-500" />
      )}
    </Button>
  );
}

export default CopyButton;
