// frontend/src/components/JQQuery.tsx
import debounce from "@/lib/debounce";
import { ChangeEvent, useCallback, useRef, useState } from "react";
import CopyButton from "./CopyButton";
import { Textarea } from "./shadcn/textarea";
import { main } from "@wails/go/models";
import { Checkbox } from "./shadcn/checkbox";

type Props = {
  onQueryChange(filter: string): void | Promise<void>;
  onFlagChange(flag: keyof main.JQFlags, value: boolean): void | Promise<void>;
};

type FlagData = {
  label: string;
  flag: string;
  enabled?: boolean;
};

const flags: Record<keyof main.JQFlags, FlagData> = {
  compact: {
    label: "Compact",
    flag: "-c",
  },
  raw: {
    label: "Raw",
    flag: "-r",
  },
  slurp: {
    label: "Slurp",
    flag: "-s",
  },
};

function getToCopy(query: string, jqFlags: typeof flags): string {
  if (query === "") {
    return "";
  }

  let result: string[] = [];

  Object.values(jqFlags).forEach((flagData) => {
    if (flagData.enabled) {
      result.push(flagData.flag);
    }
  });

  result.push(`"${query}"`);

  return result.join(" ");
}

function JQQuery(props: Props) {
  const [value, setValue] = useState("");
  const jqFlags = useRef<typeof flags>(flags);
  const debouncedQueryChange = useCallback(debounce(props.onQueryChange), [
    props.onQueryChange,
  ]);

  function handleChange(e: ChangeEvent<HTMLTextAreaElement>) {
    setValue(e.target.value);
    debouncedQueryChange(e.target.value || ".");
  }

  function handleFlagChange(flag: keyof main.JQFlags) {
    return (value: boolean) => {
      jqFlags.current[flag].enabled = value;
      props.onFlagChange(flag, value);
    };
  }

  return (
    <div className="relative group h-full p-2">
      <CopyButton
        toCopy={() => getToCopy(value, jqFlags.current)}
        className="absolute invisible opacity-0 group-hover:visible group-hover:opacity-100 transition-opacity top-2 right-4"
      />
      <Textarea
        className="resize-none h-3/4"
        placeholder="your query here"
        onChange={handleChange}
        value={value}
      />
      <div className="h-1/4 flex items-center gap-2">
        {Object.entries(flags).map(([flag, flagData]) => (
          <div className="flex items-center space-x-2" key={flag}>
            <Checkbox
              id={flag}
              onCheckedChange={handleFlagChange(flag as keyof main.JQFlags)}
            />
            <label
              htmlFor={flag}
              className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
            >
              {`${flagData.label} (${flagData.flag})`}
            </label>
          </div>
        ))}
      </div>
    </div>
  );
}

export default JQQuery;

// frontend/src/components/JQQuery.svelte
<script lang="ts">
	import { main } from "$wails/go/models";
	import CopyButton from "./CopyButton.svelte";
	import { Checkbox } from "./ui/checkbox";
	import { Textarea, type FormTextareaEvent } from "./ui/textarea";

	type FlagData = {
		label: string;
		flag: string;
	};
	const FLAGS: Record<keyof main.JQFlags, FlagData> = {
		compact: {
			label: "Compact",
			flag: "-c",
		},
		raw: {
			label: "Raw",
			flag: "-r",
		},
		slurp: {
			label: "Slurp",
			flag: "-s",
		},
	};

	export let query: string = ".";
	export let flags: main.JQFlags = {
		compact: false,
		raw: false,
		slurp: false,
	};

	function getToCopy(q: string, f: main.JQFlags): string {
		const result = Object.entries(f)
			.filter(([_, enabled]) => enabled)
			.map(([key]) => FLAGS[key as keyof main.JQFlags].flag);

		result.push(`"${q}"`);

		return result.join(" ");
	}

	$: toCopy = getToCopy(query, flags);

	function handleQueryChange(e: FormTextareaEvent<Event>) {
		const value = e.currentTarget.value;
		if (value === "") {
			query = ".";
			return;
		}

		query = value;
	}

	function handleFlagChange(flag: string) {
		return (checked: boolean | string) => {
			if (typeof checked === "string") {
				return;
			}

			flags = { ...flags, [flag]: checked };
		};
	}

	// workaround to add correct type
	function flagsToEntries() {
		return Object.entries(FLAGS) as [keyof main.JQFlags, FlagData][];
	}
</script>

<div class="relative h-full group">
	<CopyButton
		class="absolute top-4 right-4 invisible opacity-0 transition-opacity group-hover:visible group-hover:opacity-100"
		{toCopy}
	/>
	<Textarea
		class="h-3/4 resize-none"
		placeholder="your query here"
		on:input={handleQueryChange}
	/>
	<div class="flex gap-2 items-center h-1/4">
		{#each flagsToEntries() as [key, flagData] (key)}
			<Checkbox
				id={key}
				checked={flags[key]}
				onCheckedChange={handleFlagChange(key)}
			/>
			<label
				for={key}
				class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
			>
				{`${flagData.label} (${flagData.flag})`}
			</label>
		{/each}
	</div>
</div>
