// frontend/src/components/JSONHighlighter.tsx
import hljs from "highlight.js/lib/core";
import json from "highlight.js/lib/languages/json";
import "highlight.js/styles/vs.min.css";

hljs.registerLanguage("json", json);

type Props = {
  json: string;
};

// https://github.com/highlightjs/highlight.js/issues/925
function JSONHighlighter(props: Props) {
  const highlighted = hljs.highlight(props.json, { language: "json" });

  return (
    <pre>
      <code dangerouslySetInnerHTML={{ __html: highlighted.value }} />
    </pre>
  );
}

export default JSONHighlighter;

// frontend/src/components/JSONHighlighter.svelte
<script lang="ts">
	import hljs from "highlight.js/lib/core";
	import _json from "highlight.js/lib/languages/json";
	import "highlight.js/styles/vs.min.css";
	hljs.registerLanguage("json", _json);

	export let json: string = "";
</script>

<pre class="p-2">
<code>
{@html hljs.highlight(json, { language: "json" }).value}
</code>
</pre>
