// frontend/src/App.svelte
<script lang="ts">
	import JqPlayground from "$/components/JQPlayground.svelte";
	import { Button } from "$/components/ui/button";
	import ScrollArea from "$/components/ui/scroll-area/scroll-area.svelte";
	import * as Tabs from "$/components/ui/tabs";
	import formatJson from "$/lib/format-json";
	import readFileContents from "$/lib/read-file-contents";
	import { GetInitialContent } from "$wails/go/main/App";
	import type { main } from "$wails/go/models";
	import { CirclePlus, CircleX, FolderOpenDot } from "lucide-svelte";
	import { onMount } from "svelte";

	type Tab = {
		id: number;
		flags: Partial<main.JQFlags>;
		json: string;
	};

	let inputFileElement: HTMLInputElement;

	let activeTab: number;
	let id = 0;
	let tabs: Array<Tab> = [];

	function handleFlagChange(id: number) {
		return (e: CustomEvent<main.JQFlags>) => {
			tabs = tabs.map((tab) => {
				if (tab.id === id) {
					tab.flags = e.detail;
				}
				return tab;
			});
		};
	}

	function newTab(json: string, flags?: Partial<main.JQFlags>) {
		const tab = {
			id,
			json,
			flags: flags ?? {},
		};
		id++;
		tabs = [...tabs, tab];
		activeTab = tabs.length - 1;
	}

	async function handleFileChange(e: Event) {
		const target = e.target as HTMLInputElement;
		const promises = [...(target.files ?? [])].map(readFileContents);
		const results = await Promise.all(promises);
		newTab(formatJson(results.join("")), {
			slurp: results.length > 1,
		});
	}

	function closeTab(id: number) {
		const i = tabs.findIndex((tab) => tab.id === id);
		if (i > -1) {
			tabs = tabs.toSpliced(i, 1);
			if (i > 0) {
				activeTab = i - 1;
			}
		}
	}

	function handleTabChange(tab?: string) {
		if (!tab) {
			return;
		}
		activeTab = parseInt(tab);
	}

	// always creates new tab
	onMount(() => {
		GetInitialContent().then((v) => {
			newTab(formatJson(v));
		});
	});
</script>

<main class="w-screen h-screen">
	<Tabs.Root
		value={activeTab?.toString()}
		onValueChange={handleTabChange}
		class="w-full h-full"
	>
		<div class="flex gap-2 items-center px-2 h-14 bg-gray-100">
			<input
				type="file"
				id="upload"
				accept="application/json"
				bind:this={inputFileElement}
				on:change={handleFileChange}
				multiple
				hidden
			/>
			<Button
				variant="outline"
				class="space-x-1"
				on:click={() => inputFileElement.click()}
			>
				<FolderOpenDot class="text-gray-500" />
				<span>Open file(s)</span>
			</Button>
			<ScrollArea orientation="horizontal" class="max-w-80">
				<Tabs.List>
					{#each tabs as tab, i (tab.id)}
						<Tabs.Trigger value={i.toString()} on:click={() => (activeTab = i)}>
							{i + 1}
						</Tabs.Trigger>
					{/each}
				</Tabs.List>
			</ScrollArea>
			<Button
				variant="outline"
				class="p-2 space-x-1 h-8"
				on:click={() => newTab("")}
			>
				<CirclePlus class="text-gray-500" />
			</Button>
		</div>
		{#each tabs as tab, i (tab.id)}
			<Tabs.Content
				value={i.toString()}
				class="h-[calc(100%-theme(space.14))] w-full relative mt-0 group"
			>
				{#if tabs.length > 1}
					<Button
						variant="ghost"
						size="icon"
						class="absolute right-0 -top-10 z-50 p-0 bg-white rounded-full shadow-md opacity-0 transition-opacity group-hover:opacity-100 hover:bg-white"
						on:click={() => closeTab(tab.id)}
					>
						<CircleX class="text-red-600" />
					</Button>
				{/if}
				<JqPlayground
					bind:json={tab.json}
					flags={tab.flags}
					on:flagchange={handleFlagChange(tab.id)}
				/>
			</Tabs.Content>
		{/each}
	</Tabs.Root>
</main>

// frontend/src/App.tsx
import CopyButton from "@/components/CopyButton";
import JQQuery, { JQQueryRef } from "@/components/JQQuery";
import JSONHighlighter from "@/components/JSONHighlighter";
import { Button } from "@/components/shadcn/button";
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/shadcn/resizable";
import { ScrollArea, ScrollBar } from "@/components/shadcn/scroll-area";
import { Toaster } from "@/components/shadcn/sonner";
import formatJson from "@/lib/formatJson";
import generateJQFlags, { PartialJQFlags } from "@/lib/generateJQFlags";
import readFileContents from "@/lib/readFileContents";
import { Editor } from "@monaco-editor/react";
import { GetInitialContent, Query } from "@wails/go/main/App";
import { CircleX, FolderOpenDot, X } from "lucide-react";
import { editor } from "monaco-editor";
import {
  ChangeEvent,
  useDeferredValue,
  useEffect,
  useRef,
  useState,
} from "react";
import { toast } from "sonner";
import "./App.css";

const editorOptions: editor.IStandaloneEditorConstructionOptions = {
  minimap: { enabled: false },
  tabSize: 2,
  overviewRulerLanes: 0,
  scrollbar: {
    verticalScrollbarSize: 4,
    horizontalScrollbarSize: 4,
    useShadows: false,
  },
  scrollBeyondLastLine: false,
  fontSize: 16,
};

function App() {
  const [json, setJson] = useState("");
  const [jqResult, setJQResult] = useState("");
  const deferredJQResult = useDeferredValue(jqResult);
  const jqFlagsRef = useRef<PartialJQFlags>({});
  const queryStringRef = useRef(".");
  const jqQueryRef = useRef<JQQueryRef>(null);
  const inputFileRef = useRef<HTMLInputElement>(null);
  const [editorErrors, setEditorErrors] = useState<string[]>([]);

  function handleEditorChange(v?: string) {
    setJson(v ?? "");
  }

  function handleEditorValidate(markers: editor.IMarker[]) {
    const errors = markers.map(
      (marker) =>
        `${marker.message} at line ${marker.endLineNumber}, column ${marker.endColumn}`,
    );
    if (errors.length === 0) {
      toast.dismiss();
    }
    setEditorErrors(errors);
  }

  function showEditorErrors() {
    toast.dismiss();

    editorErrors.forEach((error) => {
      toast.error(error, {
        cancel: {
          label: <X className="h-4 w-4" />,
          onClick: () => {},
        },
        cancelButtonStyle: {
          backgroundColor: "inherit",
          color: "inherit",
        },
        duration: Infinity,
      });
    });
  }

  async function handleUpload(e: ChangeEvent<HTMLInputElement>) {
    const promises = [...(e.target.files ?? [])].map(readFileContents);
    const results = await Promise.all(promises);
    const slurp = jqFlagsRef.current.slurp || results.length > 1;
    const fileContents = results.join("");

    setJson(formatJson(fileContents));
    jqQueryRef.current?.setFlag("slurp", slurp);
    const result = await Query(
      fileContents,
      queryStringRef.current,
      generateJQFlags({ ...jqFlagsRef.current, slurp }),
    );

    setJQResult(result);
  }

  async function handleQueryChange(queryString: string) {
    const result = await Query(
      json,
      queryString,
      generateJQFlags(jqFlagsRef.current),
    );
    setJQResult(result);
    queryStringRef.current = queryString;
  }

  async function handleFlagChange(enabledFlags: PartialJQFlags) {
    jqFlagsRef.current = enabledFlags;
    const result = await Query(
      json,
      queryStringRef.current,
      generateJQFlags(jqFlagsRef.current),
    );
    setJQResult(result);
  }

  function openFile() {
    inputFileRef.current?.click();
  }

  useEffect(() => {
    (async () => {
      const initialContent = await GetInitialContent();
      setJson(formatJson(initialContent));
    })();
  }, []);

  return (
    <>
      <div className="h-screen">
        <div className="h-14 bg-gray-100 flex items-center px-2 gap-2">
          <input
            ref={inputFileRef}
            type="file"
            id="upload"
            accept="application/json"
            onChange={handleUpload}
            multiple
            hidden
          />
          <Button variant="outline" className="space-x-1" onClick={openFile}>
            <FolderOpenDot className="text-gray-500" />
            <span>Open file(s)</span>
          </Button>
          {editorErrors.length > 0 && (
            <Button
              variant="destructive"
              className="space-x-1"
              onClick={showEditorErrors}
            >
              <CircleX />
              <span>Show error(s)</span>
            </Button>
          )}
        </div>
        <div className="h-[calc(100%-theme(space.14))]">
          <ResizablePanelGroup direction="horizontal" className="py-2">
            <ResizablePanel defaultSize={50} className="px-2">
              <Editor
                defaultLanguage="json"
                value={json}
                onChange={handleEditorChange}
                onValidate={handleEditorValidate}
                options={editorOptions}
              />
            </ResizablePanel>
            <ResizableHandle />
            <ResizablePanel defaultSize={50} className="flex flex-col gap-2">
              <ResizablePanelGroup direction="vertical">
                <ResizablePanel defaultSize={20}>
                  <JQQuery
                    onQueryChange={handleQueryChange}
                    onFlagChange={handleFlagChange}
                    ref={jqQueryRef}
                  />
                </ResizablePanel>
                <ResizableHandle />
                <ResizablePanel defaultSize={80} className="p-2">
                  <ScrollArea className="p-2 relative group h-full">
                    <CopyButton
                      toCopy={() => jqResult}
                      className="absolute invisible opacity-0 group-hover:visible group-hover:opacity-100 transition-opacity top-2 right-4"
                    />
                    <JSONHighlighter json={deferredJQResult} />
                    <ScrollBar orientation="horizontal" />
                  </ScrollArea>
                </ResizablePanel>
              </ResizablePanelGroup>
            </ResizablePanel>
          </ResizablePanelGroup>
        </div>
      </div>
      <Toaster />
    </>
  );
}

export default App;
